fan:
  - platform: airx
    name: airx
    token: !secret airx_token
    user_id: !secret airx_user_id
    device_id: !secret airx_device_id

sensor: 
  - platform: template
    sensors:
      airx_pm25:
        friendly_name: 室内空气质量
        # icon_template: 'mdi:blur'
        value_template: '{{ states.fan.airx.attributes.pm25 }}'
        unit_of_measurement: μg/m³
      airx_outside_pm25:
        friendly_name: 室外空气质量
        # icon_template: 'mdi:blur'
        value_template: '{{ states.fan.airx.attributes.outside_pm25 }}'
        unit_of_measurement: μg/m³
      airx_remain:
        friendly_name: 滤网剩余寿命
        # icon_template: 'mdi:chemical-weapon'
        value_template: '{{ states.fan.airx.attributes.filter_remain }}'
        unit_of_measurement: '%'

group:
  airx:
    name: Airx空气净化器
    view: no
    entities:
      - fan.airx
      - sensor.airx_pm25
      - sensor.airx_outside_pm25
      - sensor.airx_remain

homeassistant:
  customize:
    fan.airx:
      friendly_name: 移动净化器
    sensor.airx_pm25:
      icon: 'mdi:blur'
    sensor.airx_outside_pm25:
      icon: 'mdi:blur'
    sensor.airx_remain:
      icon: 'mdi:chemical-weapon'
